name: build-test

on:    
  push:
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build
      - name: Set Creds
        run: git config user.name "tceglar" && git config user.email "tilen.ceglar@gmail.com"
      - name: Deploy
        run: npm run deploy

      # - run: npm run format-check
      # - run: npm test
      # - name: Verify no unstaged changes
      #   if: runner.os != 'windows'
      #   run: __tests__/verify-no-unstaged-changes.sh